### ISSUE TITLE
Basic errors in the code

### ISSUE THREAD

**Issue by nitmws** [adadgio/neo4j-js#2]
As this project looks like a simple neo4j graph editor as I need it I tried to get it working on my computer as it is shown in the video, but it failed. I tested it using Webstorm and Chrome as browser:

- Chrome debugger shows that no settings are available.
- index.html includes `<script src="settings.js"></script>` but this file is missing. The settings-sample.js file is not a JavaScript but a JSON file.
- I have adjusted the `bundles/AppBundle/Resources/Config/Mapping.js` file to my server. Line 20 of GraphController.js tries to access `Settings.client.apiEndpoint` but the variable Settings is not defined and the Mapping.js file is not referenced anywhere in the Javascript of the whole project. Looks like unlinked nodes ;-)

I'm only wondering how this example in the video worked.

**Comment by adadgio** [comment]
I'll look into these tomorrow. I'm just suspecting i havent commited the last version for a while... ;-). Keep you posted!

**Comment by nitmws** [comment]
Hi @adadgio, any progress with an update for including the settings?

**Comment by fabs-co** [comment]
Hi @adadgio, having the same issues, first one is easy to fix, just changing the name of the file and adding a variable at the beginning with the name Settings, then there is necessary to add a mime type mapping for .tpl files. But, wondering how to set up the user name and password, in the settings files there is only one authBasic.

**Comment by adadgio** [comment]
Crap... Some code had not been comited and lost.... Fell free to make a PR
!! There are a lot of feature missing indeed.

**Comment by adadgio** [comment]
Hi @nitmws ,

I have commited basic fixes on errors and updated the README accordingly (master branch). To Summarize: 

- Fixed the structure of default `settings-sample.js` (copy to `settings.js`) 
- Added some docs about how to set the auth string base64 encode of `username:password`

Would you mind retrying latest master version and keep me updated ?

**Comment by nitmws** [comment]
Cloned the app today: no errors shown when launching index.html, after selecting a Label many nodes are shown, great, a progress. Selecting a node and clicking on Edit node: a spinner is shown in this button but nothing else happens, unfortunately.

**Comment by adadgio** [comment]
Hm, editing a node works for me on Chrome. What errors do you get ?

**Comment by adadgio** [comment]
https://github.com/adadgio/neo4j-js/issues/4

**Comment by adadgio** [comment]
Note: a brand new version is here ! https://github.com/adadgio/neo4j-js-ng2
