### ISSUE TITLE
connect without username/password

### ISSUE THREAD

**Issue by kuczera** [adadgio/neo4j-js#3]
Hello,
how can i connect to a local neo4j installation without username/password ?
Greeting,
Andreas

**Comment by adadgio** [comment]
I think its more about Neo4j config, or is it ? Did you manage to connect with username/password first ?

**Comment by adadgio** [comment]
Hi @kuczera ,

This is more related to Neo4j. This project uses the REST api base64 auth string in the header (see `settings.js` and `authBasic` setting or the `README`. I don't think you can access the Neo4j REST api without this or other auth options (see [Neo4j docs](https://neo4j.com/docs/developer-manual/current/http-api/authentication/)).

This project however only support basic authentication for now.

**Comment by adadgio** [comment]
Note: a brand new version is here ! https://github.com/adadgio/neo4j-js-ng2
